# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a52f6ed0e72febf56dd611303b37623"
name = "MIXFIT"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mixfit-tdaomkyv.myshopify.com"
